# This file is part of the OpenMiamMiam project.
#
# (c) Isics <contact@isics.fr>
#
# This source file is subject to the AGPL v3 license that is bundled
# with this source code in the file LICENSE.

parameters:
    validator.mapping.loader.yaml_files_loader.mapping_files:
        - "%kernel.root_dir%/../src/Isics/Bundle/OpenMiamMiamBundle/Resources/config/validation/product.yml"
        - "%kernel.root_dir%/../src/Isics/Bundle/OpenMiamMiamBundle/Resources/config/validation/cartItem.yml"

    open_miam_miam.cart_item_validator.class:          'Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\CartItemValidator'
    open_miam_miam.buying_unit_validator.class:        'Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\BuyingUnitValidator'
    open_miam_miam.product_validator.class:            'Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\ProductValidator'
    open_miam_miam.branch_occurrence_manager.class:    'Isics\Bundle\OpenMiamMiamBundle\Manager\BranchOccurrenceManager'
    open_miam_miam.cart_manager.class:                 'Isics\Bundle\OpenMiamMiamBundle\Manager\CartManager'
    open_miam_miam.admin_manager.class:                'Isics\Bundle\OpenMiamMiamBundle\Manager\AdminManager'
    open_miam_miam.acl_manager.class:                  'Isics\Bundle\OpenMiamMiamBundle\Manager\AclManager'
    open_miam_miam.product_manager.class:              'Isics\Bundle\OpenMiamMiamBundle\Manager\ProductManager'
    open_miam_miam.menu_builder.class:                 'Isics\Bundle\OpenMiamMiamBundle\Menu\Builder'
    open_miam_miam.menu_voter.class:                   'Isics\Bundle\OpenMiamMiamBundle\Menu\Voter'
    open_miam_miam.form.type.hidden_product.class:     'Isics\Bundle\OpenMiamMiamBundle\Form\Type\HiddenProductType'
    open_miam_miam.form.type.product.class:            'Isics\Bundle\OpenMiamMiamBundle\Form\Type\Admin\ProductType'
    open_miam_miam.producer_attendances_manager.class: 'Isics\Bundle\OpenMiamMiamBundle\Manager\ProducerAttendancesManager'

services:
    # Validators
    open_miam_miam.cart_item_validator:
        class:     %open_miam_miam.cart_item_validator.class%
        arguments: [@open_miam_miam.branch_occurrence_manager]
        tags:
            - { name: validator.constraint_validator, alias: open_miam_miam_cart_item_validator}

    open_miam_miam.buying_unit_validator:
        class:     %open_miam_miam.buying_unit_validator.class%
        arguments: [%open_miam_miam.buying_units%]
        tags:
            - { name: validator.constraint_validator, alias: open_miam_miam.buying_unit_validator}

    open_miam_miam.product_validator:
        class:     %open_miam_miam.product_validator.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: open_miam_miam.product_validator}

    # Form types
    open_miam_miam.form.type.hidden_product:
        class:     %open_miam_miam.form.type.hidden_product.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: open_miam_miam_hidden_product }

    open_miam_miam.form.type.product:
        class:     %open_miam_miam.form.type.product.class%
        arguments: [%open_miam_miam.buying_units%]
        tags:
            - { name: form.type, alias: open_miam_miam_admin_product }

    # Twig extensions
    open_miam_miam.twig.open_miam_miam_extension:
        class:     Isics\Bundle\OpenMiamMiamBundle\Twig\OpenMiamMiamExtension
        arguments: [%open_miam_miam.currency%, @open_miam_miam.product_manager]
        tags:
            - { name: twig.extension }

    # Menus
    open_miam_miam.menu_builder:
        class:     %open_miam_miam.menu_builder.class%
        arguments: [@knp_menu.factory, @translator, @open_miam_miam.admin_manager]

    open_miam_miam.menu.admin:
        class:           Knp\Menu\MenuItem
        factory_service: open_miam_miam.menu_builder
        factory_method:  createAdminMenu
        tags:
            - { name: knp_menu.menu, alias: admin }

    open_miam_miam.menu_voter:
        class: %open_miam_miam.menu_voter.class%
        tags:
            - { name: knp_menu.voter, request: true }

    # Managers
    open_miam_miam.branch_occurrence_manager:
        class:     %open_miam_miam.branch_occurrence_manager.class%
        arguments: [@doctrine.orm.entity_manager]

    open_miam_miam.cart_manager:
        class:     %open_miam_miam.cart_manager.class%
        arguments: [@open_miam_miam.branch_occurrence_manager, @doctrine.orm.entity_manager, @session, @security.context]

    open_miam_miam.admin_manager:
        class: %open_miam_miam.admin_manager.class%
        arguments: [@security.context, @doctrine.orm.entity_manager]
        shared: true

    open_miam_miam.product_manager:
        class: %open_miam_miam.product_manager.class%
        arguments: [%open_miam_miam.product%, @doctrine.orm.entity_manager, @kernel]

    open_miam_miam.acl_manager:
        class:     %open_miam_miam.acl_manager.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preRemove }

    open_miam_miam.producer_attendances_manager:
        class: %open_miam_miam.producer_attendances_manager.class%
        arguments: [@doctrine.orm.entity_manager]
