# This file is part of the OpenMiamMiam project.
#
# (c) Isics <contact@isics.fr>
#
# This source file is subject to the AGPL v3 license that is bundled
# with this source code in the file LICENSE.

#
# General
#
open_miam_miam.admin:
    pattern:  /
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\General:index }

#
# Admin Producer
#
open_miam_miam.admin.producer.dashboard:
    pattern:  /producer/{id}/dashboard
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\General:showDashboard }

open_miam_miam.admin.producer.list_products:
    pattern:  /producer/{id}/products
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:list }

open_miam_miam.admin.producer.create_product:
    pattern:  /producer/{id}/products/new
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:create }

open_miam_miam.admin.producer.edit_product:
    pattern:  /producer/{id}/products/{productId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:edit }

open_miam_miam.admin.producer.delete_product:
    pattern:  /producer/{id}/products/{productId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:delete }

open_miam_miam.admin.producer.calendar:
    pattern:  /producer/{id}/calendar
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Calendar:index }

open_miam_miam.admin.producer.list_sales_order:
    pattern:  /producer/{id}/sales_order
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:list }
