# This file is part of the OpenMiamMiam project.
#
# (c) Isics <contact@isics.fr>
#
# This source file is subject to the AGPL v3 license that is bundled
# with this source code in the file LICENSE.

#
# General
#
open_miam_miam.admin:
    pattern:  /
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\General:index }



#
# Super admin
#
open_miam_miam.admin.super.show_dashboard:
    pattern:  /super/dashboard
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\General:showDashboard }

open_miam_miam.admin.super.user_switch.list:
    pattern:  /super/user-switch
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\UserSwitch:list }



#
# Admin Association
#
open_miam_miam.admin.association.show_dashboard:
    pattern:  /associations/{id}/dashboard
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\General:showDashboard }

open_miam_miam.admin.association.sales_order.list:
    pattern:  /associations/{id}/sales_orders
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:list }

open_miam_miam.admin.association.sales_order.list_for_branch_occurrence:
    pattern:  /associations/{id}/sales_orders/branch_occurrences/{branchOccurrenceId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:listForBranchOccurrence }

open_miam_miam.admin.association.sales_orders.get_sales_orders_pdf_for_branch_occurrence:
    pattern:  /associations/{id}/sales_orders/branch_occurrences/{branchOccurrenceId}/pdfs/salesOrders
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:getSalesOrdersPdfForBranchOccurrence }

open_miam_miam.admin.association.sales_order.edit:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:edit }

open_miam_miam.admin.association.sales_order.delete_row:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/rows/{salesOrderRowId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:deleteSalesOrderRow }

open_miam_miam.admin.association.sales_order.add_rows:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/rows/add
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:addSalesOrderRows }

open_miam_miam.admin.association.sales_order.pay:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/pay
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:Pay }

open_miam_miam.admin.association.sales_order.delete_payment_allocation:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/payments/allocations/{paymentAllocationId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:deletePaymentAllocation }

open_miam_miam.admin.association.sales_order.allocate_payment:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/payments/{paymentId}/allocate
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:allocatePayment }

open_miam_miam.admin.association.consumer.list:
    pattern:  /associations/{id}/consumers
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:list }

open_miam_miam.admin.association.consumer.list_payments:
    pattern:  /associations/{id}/consumers/{consumerId}/payments
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:listPayments }

open_miam_miam.admin.association.consumer.create_payment:
    pattern:  /associations/{id}/consumers/{consumerId}/payments/new
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:createPayment }

open_miam_miam.admin.association.consumer.edit_payment:
    pattern:  /associations/{id}/consumers/{consumerId}/payments/{paymentId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:editPayment }

open_miam_miam.admin.association.consumer.delete_payment:
    pattern:  /associations/{id}/consumers/{consumerId}/payments/{paymentId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:deletePayment }

open_miam_miam.admin.association.consumer.delete_payment_allocation:
    pattern: /associations/{id}/consumers/{consumerId}/payments/allocations/{paymentAllocationId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:deletePaymentAllocation }

open_miam_miam.admin.association.consumer.allocate_sales_order:
    pattern:  /associations/{id}/consumers/{consumerId}/payments/{paymentId}/allocate_sales_order/{salesOrderId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:allocateSalesOrder }



#
# Admin Producer
#
open_miam_miam.admin.producer.show_dashboard:
    pattern:  /producers/{id}/dashboard
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\General:showDashboard }

open_miam_miam.admin.producer.edit:
    pattern:  /producers/{id}/edit
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\General:edit }

open_miam_miam.admin.producer.product.list:
    pattern:  /producers/{id}/products
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:list }

open_miam_miam.admin.producer.product.create:
    pattern:  /producers/{id}/products/new
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:create }

open_miam_miam.admin.producer.product.edit:
    pattern:  /producers/{id}/products/{productId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:edit }

open_miam_miam.admin.producer.product.delete:
    pattern:  /producers/{id}/products/{productId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:delete }

open_miam_miam.admin.producer.calendar.edit:
    pattern:  /producers/{id}/calendar
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Calendar:edit }

open_miam_miam.admin.producer.sales_order.list:
    pattern:  /producers/{id}/sales_orders
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:list }

open_miam_miam.admin.producer.sales_order.edit:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:edit }

open_miam_miam.admin.producer.sales_order.add_rows:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}/rows/add
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:addSalesOrderRows }

open_miam_miam.admin.producer.sales_order.delete_row:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}/rows/{salesOrderRowId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:deleteSalesOrderRow }
