# This file is part of the OpenMiamMiam project.
#
# (c) Isics <contact@isics.fr>
#
# This source file is subject to the AGPL v3 license that is bundled
# with this source code in the file LICENSE.

#
# General
#
open_miam_miam.admin:
    pattern:  /
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\General:index }



#
# Admin Association
#
open_miam_miam.admin.association.show_dashboard:
    pattern:  /associations/{id}/dashboard
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\General:showDashboard }

open_miam_miam.admin.association.sales_order.list:
    pattern:  /associations/{id}/sales_orders
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:list }

open_miam_miam.admin.association.sales_order.list_for_branch_occurrence:
    pattern:  /associations/{id}/sales_orders/branch_occurrences/{branchOccurrenceId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:listForBranchOccurrence }



#
# Admin Producer
#
open_miam_miam.admin.producer.show_dashboard:
    pattern:  /producers/{id}/dashboard
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\General:showDashboard }

open_miam_miam.admin.producer.edit:
    pattern:  /producers/{id}/edit
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\General:edit }

open_miam_miam.admin.producer.product.list:
    pattern:  /producers/{id}/products
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:list }

open_miam_miam.admin.producer.product.create:
    pattern:  /producers/{id}/products/new
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:create }

open_miam_miam.admin.producer.product.edit:
    pattern:  /producers/{id}/products/{productId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:edit }

open_miam_miam.admin.producer.product.delete:
    pattern:  /producers/{id}/products/{productId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:delete }

open_miam_miam.admin.producer.calendar.edit:
    pattern:  /producers/{id}/calendar
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Calendar:edit }

open_miam_miam.admin.producer.sales_order.list:
    pattern:  /producers/{id}/sales_orders
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:list }

open_miam_miam.admin.producer.sales_order.edit:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:edit }

open_miam_miam.admin.producer.sales_order.add_rows:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}/rows/add
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:addSalesOrderRows }

open_miam_miam.admin.producer.sales_order.delete_row:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}/rows/{salesOrderRowId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:deleteSalesOrderRow }

