Isics\Bundle\OpenMiamMiamBundle\Entity\BranchOccurrence:
    constraints:
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\BranchOccurrence: ~
    properties:
        branch:
            - NotNull: ~
            - Valid: ~
        begin:
            - NotNull: ~
            - DateTime: ~
        end:
            - NotNull: ~
            - DateTime: ~