Isics\Bundle\OpenMiamMiamBundle\Entity\Newsletter:
    properties:
        recipientType:
            - NotNull: ~
        subject:
            - NotNull: ~
            - Length:
                max: 128
        body:
            - NotNull: ~
        sentAt:
            - DateTime: ~
