Isics\Bundle\OpenMiamMiamBundle\Model\ProducerAttendances:
    properties:
        producer:
            - Valid: ~
            - NotNull: ~
        branchAttendances:
            - Valid: ~

Isics\Bundle\OpenMiamMiamBundle\Model\ProducerBranchAttendances:
    properties:
        producer:
            - Valid: ~
            - NotNull: ~
        branch:
            - Valid: ~
            - NotNull: ~
        branchOccurrenceAttendances:
            - Valid: ~

Isics\Bundle\OpenMiamMiamBundle\Model\ProducerBranchOccurrenceAttendance:
    constraints:
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\ProducerBranchOccurrenceAttendance: ~
    properties:
        producer:
            - Valid: ~
            - NotNull: ~
        branchOccurrence:
            - Valid: ~
            - NotNull: ~
        attendance:
            - Choice: { callback: getAttendancesStatus}
