Isics\Bundle\OpenMiamMiamBundle\Entity\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: ref
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\Product:
    properties:
        name:
            - NotNull: ~
            - Length:
                max: 128
        ref:
            - NotNull: ~
            - Length:
                max: 16
        category:
            - NotNull: ~
        isBio:
            - Type: bool
        isOfTheMoment:
            - Type: bool
        description:
            - Length:
                max: 255
        price:
            - Range:
                min: 0.01
        priceInfo:
            - Length:
                max: 128
        imageFile:
            - Image:
                maxSize: 5120k
        deleteImage:
            - Type: bool
        hasPrice:
            - Type: bool
        buyingUnit:
            - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\BuyingUnit: ~
        allowDecimalQuantity:
            - Type: bool
        availability:
            - Choice: { callback: getAvailabilityStatus}
        stock:
            - Range:
                min: 0
        availableAt:
            - Date: ~
