services:
    open_miam_miam.form.type.user_registration:
        class: Isics\Bundle\OpenMiamMiamUserBundle\Form\Type\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: open_miam_miam_user_registration }

    open_miam_miam.form.type.user_profile:
        class: Isics\Bundle\OpenMiamMiamUserBundle\Form\Type\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: open_miam_miam_user_profile }

    open_miam_miam_user.listener.profile_editing:
        class: Isics\Bundle\OpenMiamMiamUserBundle\EventListener\ProfileEditingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
